/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.MenuPrincipalController;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author iara4
 */
public class MenuPrincipal extends javax.swing.JFrame {

    private final MenuPrincipalController controller;
    private String tipoUsuario;
     private String nivelAcesso;


    private void aplicarRestricoes() {
        if ("medico".equalsIgnoreCase(nivelAcesso)) {
            btnCadastrarPaciente.setEnabled(false);
            btnCadastrarMedico.setEnabled(false);
        }
    }
    

    private void cadastrarPaciente() {
        if (!btnCadastrarPaciente.isEnabled()) {
            JOptionPane.showMessageDialog(this, "Acesso negado! Somente administradores podem cadastrar pacientes.");
            return;
        }
        // Código para cadastrar paciente
    }

    private void cadastrarMedico() {
        if (!btnCadastrarMedico.isEnabled()) {
            JOptionPane.showMessageDialog(this, "Acesso negado! Somente administradores podem cadastrar médicos.");
            return;
        }
        // Código para cadastrar médico
    }

    private JButton btnCadastrarPaciente;
    private JButton btnCadastrarMedico;
    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        this.controller = new MenuPrincipalController(this);
        this.nivelAcesso = nivelAcesso;
        aplicarRestricoes();
    }

   
    public MenuPrincipal(String tipoUsuario) {
        this.tipoUsuario = tipoUsuario;
        initComponents();
        this.controller = new MenuPrincipalController(this);
        configurarAcessos();
    }

    private void configurarAcessos() {
        if (tipoUsuario.equals("Médico")) {
            CadastrarMedico.setVisible(false);
        } else if (tipoUsuario.equals("Administrador")) {
            // O Administrador pode ver tudo, então não escondemos nada
        } else {
            // Caso de um usuário comum, podemos ocultar mais opções
            CadastrarMedico.setVisible(false);
            CadastrarPaciente.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCadastro = new javax.swing.JMenu();
        CadastrarPaciente = new javax.swing.JMenuItem();
        CadastrarMedico = new javax.swing.JMenuItem();
        jMenuOperacoes = new javax.swing.JMenu();
        AgendarConsulta = new javax.swing.JMenuItem();
        jmenu = new javax.swing.JMenu();
        NavegarRelatorio = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Principal");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, 70, 80));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/BackgroundMenuPrincipal.png"))); // NOI18N
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jMenuCadastro.setText("Cadastro");

        CadastrarPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cliente-icon.png"))); // NOI18N
        CadastrarPaciente.setText("Paciente");
        CadastrarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarPacienteActionPerformed(evt);
            }
        });
        jMenuCadastro.add(CadastrarPaciente);

        CadastrarMedico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/tesoura.icon.png"))); // NOI18N
        CadastrarMedico.setText("Medico");
        CadastrarMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarMedicoActionPerformed(evt);
            }
        });
        jMenuCadastro.add(CadastrarMedico);

        jMenuBar1.add(jMenuCadastro);

        jMenuOperacoes.setText("Operações");

        AgendarConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/agenda-icon.png"))); // NOI18N
        AgendarConsulta.setText("Agenda");
        AgendarConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgendarConsultaActionPerformed(evt);
            }
        });
        jMenuOperacoes.add(AgendarConsulta);

        jMenuBar1.add(jMenuOperacoes);

        jmenu.setText("Relatorio");
        jmenu.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jmenuItemStateChanged(evt);
            }
        });
        jmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuActionPerformed(evt);
            }
        });

        NavegarRelatorio.setText("Relatorio");
        NavegarRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NavegarRelatorioActionPerformed(evt);
            }
        });
        jmenu.add(NavegarRelatorio);

        jMenuBar1.add(jmenu);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AgendarConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgendarConsultaActionPerformed
        try {
            this.controller.navegarParaAgenda();
        } catch (ParseException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_AgendarConsultaActionPerformed

    private void CadastrarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarPacienteActionPerformed
         try {
            this.controller.navegarParaCadastrarPaciente();
        } catch (ParseException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }// TODO add your handling code here:
    }//GEN-LAST:event_CadastrarPacienteActionPerformed

    private void CadastrarMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarMedicoActionPerformed
         try {
            this.controller.navegarParaCadastrarMedico();
        } catch (ParseException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }// TODO add your handling code here:
    }//GEN-LAST:event_CadastrarMedicoActionPerformed

    private void jmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuActionPerformed
        try {
            this.controller.navegarParaRelatorio();
        } catch (ParseException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jmenuActionPerformed

    private void jmenuItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jmenuItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jmenuItemStateChanged

    private void NavegarRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NavegarRelatorioActionPerformed
        try {
            this.controller.navegarParaRelatorio();
        } catch (ParseException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_NavegarRelatorioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AgendarConsulta;
    private javax.swing.JMenuItem CadastrarMedico;
    private javax.swing.JMenuItem CadastrarPaciente;
    private javax.swing.JMenuItem NavegarRelatorio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCadastro;
    private javax.swing.JMenu jMenuOperacoes;
    private javax.swing.JMenu jmenu;
    // End of variables declaration//GEN-END:variables
}
